#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:

  # CAs
  ca.org1.example.com:
    extends:
      file: base/base.yaml
      service: ca-base
    container_name: ca.org1.example.com
    environment:
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com_sk
    ports:
      - "7054:7054"
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  ca.org2.example.com:
    extends:
      file: base/base.yaml
      service: ca-base
    container_name: ca.org2.example.com
    environment:
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com_sk
    ports:
      - "8054:7054"
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  ca.org3.example.com:
    extends:
      file: base/base.yaml
      service: ca-base
    container_name: ca.org3.example.com
    environment:
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com_sk
    ports:
      - "9054:7054"
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  ca.org4.example.com:
    extends:
      file: base/base.yaml
      service: ca-base
    container_name: ca.org4.example.com
    environment:
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org4.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.org4.example.com_sk
    ports:
      - "10054:7054"
    volumes:
      - ./crypto-config/peerOrganizations/org4.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/msp/peerOrg1
        - ./orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
    networks:
      - basic

  peer0.org1.example.com:
    extends:
      file: base/peer-base.yaml
      service: peer0.org1.example.com 
    depends_on:
      - orderer.example.com
    networks:
      - basic

  peer0.org2.example.com:
    extends:
      file: base/peer-base.yaml
      service: peer0.org2.example.com 
    depends_on:
      - orderer.example.com
    networks:
      - basic

  peer0.org3.example.com:
    extends:
      file: base/peer-base.yaml
      service: peer0.org3.example.com 
    depends_on:
      - orderer.example.com
    networks:
      - basic

  peer0.org4.example.com:
    extends:
      file: base/peer-base.yaml
      service: peer0.org4.example.com 
    depends_on:
      - orderer.example.com
    networks:
      - basic
